language: node_js

sudo: false

matrix:
  include:
    - node_js: node
      script:
        - npm run-script danger
        - npm run-script coverage
      after_script:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

node_js:
  - 4
  - 5
  - 6
  - 8
  - 9

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

notifications:
  email: false
